### ISSUE TITLE
Broken download link on website

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-project/pharo-website#70]
Originally reported here: https://github.com/pharo-project/pharo/issues/16536 by igouy

https://pharo.org/download page

Pharo image: [64bit (default)](https://files.pharo.org/get-files/120/pharo64.zip)

Not Found

The requested URL was not found on this server.

**Comment by MarcusDenker** [comment]
fixed by https://github.com/pharo-project/pharo-website/pull/71
