### ISSUE TITLE
is twitter still relevant on documentation?

### ISSUE THREAD

**Issue by Ducasse** [pharo-project/pharo-website#77]
```
### On Twitter

Follow on twitter to get notified of new pages: [https://twitter.com/PharoOpen](https://twitter.com/PharoOpen)
```

Ma be should remove it.

**Comment by Ducasse** [comment]
I cannot test I do not have an account on this bad platform. We should continue to boycott such terrible media.

**Comment by MarcusDenker** [comment]
We should unify all twitter account to use the main one. That one we feed via the tool (and at the same time facebook and linkedIn).

**Comment by Ducasse** [comment]
This is another issue. 
So I will remove the reference to the twitter account.
